version: "3.7"
services: 
  app:
    build:
      args:
        user: andi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: attanox/rtd-planner
    container_name: rtd-planner-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - rtd-planner
  nginx:
    image: nginx:1.17-alpine
    container_name: rtd-planner-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - rtd-planner


networks:
  rtd-planner:
    driver: bridge
